// Static provider config — no DB imports. Safe to import from scripts.
// ai-video-providers.ts re-exports everything from here.
//
// PROVIDER_TEST_ID_MAP lives here (not in ai-video-providers.ts) so that
// scripts/check-provider-catalog-sync.ts can import it without pulling in
// any DB dependencies.

export interface AIVideoProviderConfig {
  modelId: string;
  apiProvider: string;
  costPerSecond: number;
  maxDuration: number;
  name?: string;
  type?: 'piapi' | 'direct';
  capabilities: {
    t2v: boolean;
    i2v: boolean;
    v2v: boolean;
  };
  supportedAspectRatios: string[];
}

// Maps each provider key to the PiAPI test IDs whose pass/fail status
// controls whether the provider is included in the live dropdown.
// Every showInDropdown:true entry in VIDEO_PROVIDER_CATALOG must appear here.
// The lint check in scripts/check-provider-catalog-sync.ts enforces this.
export const PROVIDER_TEST_ID_MAP: Record<string, string[]> = {
  'omni-human-1.5': ['omnihuman-1.5'],
  'kling-avatar': ['i2v-kling-avatar'],
  'omniavatar': ['i2v-omniavatar'],
  'kling-2.6': ['kling-2.6'],
  'kling-2.6-pro': ['kling-2.6'],
  'kling-2.1-master': ['kling-2.6'],
  'kling-2.6-motion-control-pro': ['kling-2.6'],
  'kling-2.5': ['kling-2.5'],
  'kling-effects': ['kling-effects'],
  'veo-3.1': ['veo-3.1'],
  'veo-3': ['veo-3'],
  'luma': ['luma'],
  'runway': ['runway'],
  'runway-4.5': ['runway-4.5'],
  'runway-gen4': ['runway-gen4'],
  'runway-gen4-aleph': ['runway-gen4-aleph'],
  'runway-act-two': ['runway-act-two'],
  'runway-aleph-2': ['runway-aleph-2'],
  'runway-agent-2': ['runway-agent-2'],
  'runway-happy-horse-1': ['runway-happy-horse-1'],
  'hailuo': ['hailuo'],
  'wan-2.6': ['wan-2.6'],
  'pika': ['pika'],
  'seedance-1.0': ['seedance-1.0', 'seedance-pro'],
  'seedance-2.0': ['seedance-2'],
  'seedance-2.0-fast': ['seedance-2-fast'],
  'seedance-2-lr': ['seedance-2'],
  'sora-2': ['sora-2'],
  'sora-2-pro': ['sora-2-pro'],
  'hunyuan': ['hunyuan'],
};

export const AI_VIDEO_PROVIDERS: Record<string, AIVideoProviderConfig> = {
  'kling': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.03,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-1.6': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.025,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.0': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.03,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.1': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.035,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.1-master': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.19,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.5': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.039,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.5-turbo': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.04,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.6': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.039,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.6-pro': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.066,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.6-motion-control': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.066,
    maxDuration: 30,
    capabilities: { t2v: true, i2v: true, v2v: true },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-2.6-motion-control-pro': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.08,
    maxDuration: 30,
    capabilities: { t2v: true, i2v: true, v2v: true },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-avatar': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.045,
    maxDuration: 60,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'kling-effects': {
    modelId: 'kling',
    apiProvider: 'piapi',
    costPerSecond: 0.02,
    maxDuration: 5,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'luma': {
    modelId: 'luma',
    apiProvider: 'piapi',
    costPerSecond: 0.04,
    maxDuration: 5,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'luma-dream-machine': {
    modelId: 'luma',
    apiProvider: 'piapi',
    costPerSecond: 0.04,
    maxDuration: 5,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'runway': {
    modelId: 'runway',
    apiProvider: 'runway',
    type: 'direct',
    costPerSecond: 0.05,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'runway-4.5': {
    modelId: 'runway-4.5',
    apiProvider: 'runway',
    type: 'direct',
    name: 'Runway 4.5',
    costPerSecond: 0.07,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'runway-gen4': {
    modelId: 'runway-gen4',
    apiProvider: 'runway',
    type: 'direct',
    name: 'Runway Gen-4',
    costPerSecond: 0.05,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'runway-gen4-aleph': {
    modelId: 'runway-gen4-aleph',
    apiProvider: 'runway',
    type: 'direct',
    name: 'Runway Gen-4 Aleph',
    costPerSecond: 0.06,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'runway-act-two': {
    modelId: 'runway-act-two',
    apiProvider: 'runway',
    type: 'direct',
    name: 'Runway Act Two',
    costPerSecond: 0.06,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'runway-aleph-2': {
    modelId: 'runway-aleph-2',
    apiProvider: 'runway',
    type: 'direct',
    name: 'Runway Aleph 2.0',
    costPerSecond: 0.09,
    maxDuration: 10,
    capabilities: { t2v: false, i2v: false, v2v: true },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'runway-agent-2': {
    modelId: 'runway-agent-2',
    apiProvider: 'runway',
    type: 'direct',
    name: 'Runway Agent 2.0',
    costPerSecond: 0.1,
    maxDuration: 30,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'runway-happy-horse-1': {
    modelId: 'runway-happy-horse-1',
    apiProvider: 'runway',
    type: 'direct',
    name: 'Runway Happy Horse 1.0',
    costPerSecond: 0.08,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'hailuo': {
    modelId: 'hailuo',
    apiProvider: 'piapi',
    costPerSecond: 0.02,
    maxDuration: 6,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'hailuo-minimax': {
    modelId: 'hailuo',
    apiProvider: 'piapi',
    costPerSecond: 0.015,
    maxDuration: 6,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'seedance-1.0': {
    modelId: 'hailuo',
    apiProvider: 'piapi',
    costPerSecond: 0.035,
    maxDuration: 6,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'seedance-2.0': {
    modelId: 'seedance',
    apiProvider: 'piapi',
    costPerSecond: 0.035,
    maxDuration: 15,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'seedance-2.0-fast': {
    modelId: 'seedance',
    apiProvider: 'piapi',
    costPerSecond: 0.020,
    maxDuration: 15,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'seedance-2-lr': {
    modelId: 'seedance',
    apiProvider: 'piapi',
    costPerSecond: 0.035,
    maxDuration: 15,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'pika': {
    modelId: 'pika',
    apiProvider: 'piapi',
    costPerSecond: 0.04,
    maxDuration: 5,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'genmo': {
    modelId: 'genmo',
    apiProvider: 'piapi',
    costPerSecond: 0.03,
    maxDuration: 8,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'hunyuan': {
    modelId: 'hunyuan',
    apiProvider: 'piapi',
    costPerSecond: 0.025,
    maxDuration: 5,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'skyreels': {
    modelId: 'skyreels',
    apiProvider: 'piapi',
    costPerSecond: 0.03,
    maxDuration: 5,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'wan-2.1': {
    modelId: 'wan-2.1',
    apiProvider: 'piapi',
    costPerSecond: 0.025,
    maxDuration: 5,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'wan-2.6': {
    modelId: 'wan-2.6',
    apiProvider: 'piapi',
    costPerSecond: 0.03,
    maxDuration: 5,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'veo': {
    modelId: 'veo3',
    apiProvider: 'piapi',
    costPerSecond: 0.06,
    maxDuration: 8,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'veo-2': {
    modelId: 'veo2',
    apiProvider: 'piapi',
    costPerSecond: 0.055,
    maxDuration: 8,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'veo-3': {
    modelId: 'veo3',
    apiProvider: 'piapi',
    costPerSecond: 0.06,
    maxDuration: 8,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'veo-3.1': {
    modelId: 'veo3.1',
    apiProvider: 'piapi',
    costPerSecond: 0.065,
    maxDuration: 8,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'veo2': {
    modelId: 'veo2',
    apiProvider: 'piapi',
    costPerSecond: 0.055,
    maxDuration: 8,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'veo3': {
    modelId: 'veo3',
    apiProvider: 'piapi',
    costPerSecond: 0.06,
    maxDuration: 8,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'veo3.1': {
    modelId: 'veo3.1',
    apiProvider: 'piapi',
    costPerSecond: 0.065,
    maxDuration: 8,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'sora-2': {
    modelId: 'sora2',
    apiProvider: 'piapi',
    costPerSecond: 0.08,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: false, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'sora-2-pro': {
    modelId: 'sora2',
    apiProvider: 'piapi',
    costPerSecond: 0.12,
    maxDuration: 10,
    capabilities: { t2v: true, i2v: false, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'omni-human-1.5': {
    modelId: 'omni-human',
    apiProvider: 'piapi',
    costPerSecond: 0.05,
    maxDuration: 30,
    capabilities: { t2v: false, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
  'omniavatar': {
    modelId: 'omniavatar',
    apiProvider: 'piapi',
    costPerSecond: 0.045,
    maxDuration: 30,
    capabilities: { t2v: true, i2v: true, v2v: false },
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
  },
};
