export interface ProviderCatalogEntry {
  id: string;
  name: string;
  family: string;
  description: string;
  capabilities: string[];
  maxDuration: number;
  costTier: 'budget' | 'standard' | 'premium' | 'ultra';
  type: 'video' | 'image';
  supportedModes: ('t2v' | 'i2v' | 'v2v' | 't2i')[];
  aspectRatios: string[];
  highlight?: string;
}

export const VIDEO_PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: 'kling',
    name: 'Kling 1.0 (Legacy)',
    family: 'Kling',
    description: 'Original Kling model. Superseded by Kling 2.6 — use Kling 2.6 or Auto-select for best results.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'kling-1.6',
    name: 'Kling 1.6',
    family: 'Kling',
    description: 'Improved motion consistency and visual fidelity over the original. Great entry point for Kling-family models at a lower cost.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'budget',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'kling-2.0',
    name: 'Kling 2.0',
    family: 'Kling',
    description: 'Second-generation model with enhanced scene understanding, better camera movements, and improved temporal consistency.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'kling-2.1',
    name: 'Kling 2.1',
    family: 'Kling',
    description: 'Refined character consistency and natural motion. Excellent for product demos and lifestyle content with smooth transitions.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'kling-2.1-master',
    name: 'Kling 2.1 Master',
    family: 'Kling',
    description: 'Premium tier of Kling 2.1 with maximum quality rendering. Best for hero content, cinematic sequences, and high-stakes productions.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'ultra',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Premium Quality',
  },
  {
    id: 'kling-2.5',
    name: 'Kling 2.5',
    family: 'Kling',
    description: 'Advanced prompt understanding with cinematic lighting. Produces film-quality footage with natural depth of field and color grading.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'kling-2.5-turbo',
    name: 'Kling 2.5 Turbo',
    family: 'Kling',
    description: 'Faster rendering variant of Kling 2.5. Maintains high quality with significantly reduced generation time — ideal for iterating quickly.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Fast',
  },
  {
    id: 'kling-2.6',
    name: 'Kling 2.6',
    family: 'Kling',
    description: 'Latest standard Kling model. Excellent character consistency, realistic physics, and top-tier prompt adherence for marketing and social content.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Recommended',
  },
  {
    id: 'kling-2.6-pro',
    name: 'Kling 2.6 Pro',
    family: 'Kling',
    description: 'Professional-grade Kling 2.6 with enhanced detail rendering, superior lighting, and broadcast-ready output quality.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'kling-2.6-motion-control',
    name: 'Kling 2.6 Motion Control',
    family: 'Kling',
    description: 'Adds precise camera path and motion control to Kling 2.6. Direct pan, zoom, orbit, and dolly movements for cinematic storytelling.',
    capabilities: ['T2V', 'I2V', 'V2V'],
    maxDuration: 30,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v', 'v2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Camera Control',
  },
  {
    id: 'kling-2.6-motion-control-pro',
    name: 'Kling 2.6 Motion Control Pro',
    family: 'Kling',
    description: 'Premium motion control with maximum quality. Combines Kling\'s best rendering with advanced camera choreography for professional productions.',
    capabilities: ['T2V', 'I2V', 'V2V'],
    maxDuration: 30,
    costTier: 'ultra',
    type: 'video',
    supportedModes: ['t2v', 'i2v', 'v2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'kling-avatar',
    name: 'Kling Avatar',
    family: 'Kling',
    description: 'Specialized for talking-head and avatar videos. Native lip-sync, consistent character identity, and natural expressions — perfect for presenters and spokespersons.',
    capabilities: ['T2V', 'I2V', 'Lip-Sync'],
    maxDuration: 60,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Lip-Sync',
  },
  {
    id: 'kling-effects',
    name: 'Kling Effects',
    family: 'Kling',
    description: 'Quick special effects and visual transformations. Generate short VFX clips, particle effects, and stylized transitions at low cost.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 5,
    costTier: 'budget',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'luma',
    name: 'Luma',
    family: 'Luma',
    description: 'Luma AI\'s Dream Machine model. Excels at photorealistic scenes with natural lighting, atmospheric depth, and smooth camera motion.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 5,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    family: 'Luma',
    description: 'Full Dream Machine model with enhanced creative control. Beautiful cinematic output with dreamy aesthetics and imaginative scene composition.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 5,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'runway',
    name: 'Runway Gen-3',
    family: 'Runway',
    description: 'RunwayML\'s Gen-3 model via direct API. Industry-leading prompt comprehension, cinematic quality, and reliable multi-subject scenes for professional video production.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Industry Standard',
  },
  {
    id: 'runway-4.5',
    name: 'Runway 4.5',
    family: 'Runway',
    description: 'Runway\'s latest and most powerful model. Top-tier photorealistic motion, advanced camera manipulation, and the best creative control available. Direct API.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Latest Runway',
  },
  {
    id: 'runway-gen4',
    name: 'Runway Gen-4',
    family: 'Runway',
    description: 'Gen-4 standard model with advanced creative control, motion manipulation, and dramatic storytelling capabilities. Direct API integration.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'runway-gen4-aleph',
    name: 'Runway Gen-4 Aleph',
    family: 'Runway',
    description: 'Gen-4 Aleph variant with enhanced creative control and superior motion quality. Excels at dramatic lighting and advanced cinematic composition. Direct API.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Creative Control',
  },
  {
    id: 'runway-act-two',
    name: 'Runway Act Two',
    family: 'Runway',
    description: 'Specialized for character performance and acting. Generates expressive body language, emotional facial performance, and natural character interactions. Direct API.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 10,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Character Acting',
  },
  {
    id: 'hailuo',
    name: 'Hailuo',
    family: 'Hailuo',
    description: 'MiniMax\'s Hailuo model with strong motion dynamics and vivid colors. Great value for social media content with eye-catching visual style.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 6,
    costTier: 'budget',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'hailuo-minimax',
    name: 'Hailuo MiniMax',
    family: 'Hailuo',
    description: 'Optimized MiniMax variant with fast generation and consistent output. Budget-friendly choice for high-volume content creation.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 6,
    costTier: 'budget',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Best Value',
  },
  {
    id: 'seedance-1.0',
    name: 'Seedance 1.0',
    family: 'Hailuo',
    description: 'Specialized dance and rhythmic motion model. Creates fluid body movements and choreography — ideal for music videos and dance content.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 6,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Dance & Motion',
  },
  {
    id: 'pika',
    name: 'Pika',
    family: 'Pika',
    description: 'Pika Labs\' creative video model. Known for artistic stylization, bold visual effects, and creative interpretations of prompts.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 5,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'genmo',
    name: 'Genmo Mochi',
    family: 'Genmo',
    description: 'Genmo\'s Mochi model with smooth, consistent motion and clean aesthetic. Good for explainer videos and product showcases with natural movement.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 8,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'hunyuan',
    name: 'Hunyuan',
    family: 'Hunyuan',
    description: 'Tencent\'s Hunyuan video model. Strong at generating complex scenes with multiple elements, detailed backgrounds, and natural interactions.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 5,
    costTier: 'budget',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'skyreels',
    name: 'SkyReels',
    family: 'SkyReels',
    description: 'Cinematic-focused model with film-like composition and dramatic lighting. Excels at landscape, aerial, and establishing shots.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 5,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'wan-2.1',
    name: 'Wan 2.1',
    family: 'Wan',
    description: 'Alibaba\'s Wan model with excellent text rendering in videos and strong character consistency. Great for branded content with on-screen text.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 5,
    costTier: 'budget',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'wan-2.6',
    name: 'Wan 2.6',
    family: 'Wan',
    description: 'Latest Wan model with improved visual quality and motion. Better physics simulation and more coherent multi-object scenes than 2.1.',
    capabilities: ['T2V', 'I2V'],
    maxDuration: 5,
    costTier: 'standard',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'veo',
    name: 'Veo',
    family: 'Veo',
    description: 'Google DeepMind\'s Veo model with native audio generation. Creates videos with synchronized sound effects and ambient audio built in.',
    capabilities: ['T2V', 'I2V', 'Audio'],
    maxDuration: 8,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Native Audio',
  },
  {
    id: 'veo-2',
    name: 'Veo 2',
    family: 'Veo',
    description: 'Second-generation Veo with improved visual coherence and more realistic physics. Enhanced audio synchronization and environmental sounds.',
    capabilities: ['T2V', 'I2V', 'Audio'],
    maxDuration: 8,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'veo-3',
    name: 'Veo 3',
    family: 'Veo',
    description: 'Google\'s most advanced video model. Cinematic quality with native dialogue, sound effects, and music generation. State-of-the-art realism.',
    capabilities: ['T2V', 'I2V', 'Audio', 'Dialogue'],
    maxDuration: 8,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Top Tier',
  },
  {
    id: 'veo-3.1',
    name: 'Veo 3.1',
    family: 'Veo',
    description: 'Latest Veo with the highest fidelity output. Best-in-class for photorealistic scenes with complex lighting, natural dialogue, and immersive soundscapes.',
    capabilities: ['T2V', 'I2V', 'Audio', 'Dialogue'],
    maxDuration: 8,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Latest & Best',
  },
  {
    id: 'veo2',
    name: 'Veo2 (Alias)',
    family: 'Veo',
    description: 'Alias for Veo 2. Same model — use "veo-2" for consistency.',
    capabilities: ['T2V', 'I2V', 'Audio'],
    maxDuration: 8,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'veo3',
    name: 'Veo3 (Alias)',
    family: 'Veo',
    description: 'Alias for Veo 3. Same model — use "veo-3" for consistency.',
    capabilities: ['T2V', 'I2V', 'Audio', 'Dialogue'],
    maxDuration: 8,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'veo3.1',
    name: 'Veo3.1 (Alias)',
    family: 'Veo',
    description: 'Alias for Veo 3.1. Same model — use "veo-3.1" for consistency.',
    capabilities: ['T2V', 'I2V', 'Audio', 'Dialogue'],
    maxDuration: 8,
    costTier: 'premium',
    type: 'video',
    supportedModes: ['t2v', 'i2v'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
];

export const IMAGE_PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: 'flux',
    name: 'Flux',
    family: 'Flux',
    description: 'Black Forest Labs\' Flux model. Fast, high-quality image generation with excellent prompt adherence and photorealistic output.',
    capabilities: ['T2I'],
    maxDuration: 0,
    costTier: 'standard',
    type: 'image',
    supportedModes: ['t2i'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Recommended',
  },
  {
    id: 'flux-1-dev',
    name: 'Flux 1 Dev',
    family: 'Flux',
    description: 'Developer variant of Flux with lower cost. Great for rapid prototyping and bulk image generation at a budget-friendly price.',
    capabilities: ['T2I'],
    maxDuration: 0,
    costTier: 'budget',
    type: 'image',
    supportedModes: ['t2i'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'stability',
    name: 'Stable Diffusion 3',
    family: 'Stability',
    description: 'Stability AI\'s latest diffusion model. Exceptional text rendering in images, versatile style range, and consistent compositional quality.',
    capabilities: ['T2I'],
    maxDuration: 0,
    costTier: 'budget',
    type: 'image',
    supportedModes: ['t2i'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    family: 'Ideogram',
    description: 'Best-in-class text rendering in images. Perfect for marketing materials, social graphics, and any content requiring readable text overlays.',
    capabilities: ['T2I'],
    maxDuration: 0,
    costTier: 'standard',
    type: 'image',
    supportedModes: ['t2i'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Best Text',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    family: 'Midjourney',
    description: 'Industry-leading aesthetic quality. Produces stunning, artistic images with beautiful composition, lighting, and rich visual detail.',
    capabilities: ['T2I'],
    maxDuration: 0,
    costTier: 'premium',
    type: 'image',
    supportedModes: ['t2i'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Best Aesthetic',
  },
  {
    id: 'dalle3',
    name: 'DALL-E 3',
    family: 'OpenAI',
    description: 'OpenAI\'s latest image model. Strong prompt understanding, creative interpretation, and reliable quality across diverse subjects and styles.',
    capabilities: ['T2I'],
    maxDuration: 0,
    costTier: 'standard',
    type: 'image',
    supportedModes: ['t2i'],
    aspectRatios: ['16:9', '9:16', '1:1'],
  },
  {
    id: 'falai',
    name: 'Fal AI',
    family: 'Fal',
    description: 'Fast inference image generation. Optimized for speed with good quality output — ideal for real-time applications and rapid iteration.',
    capabilities: ['T2I'],
    maxDuration: 0,
    costTier: 'budget',
    type: 'image',
    supportedModes: ['t2i'],
    aspectRatios: ['16:9', '9:16', '1:1'],
    highlight: 'Fastest',
  },
];

export const COST_TIER_LABELS: Record<string, { label: string; color: string }> = {
  budget: { label: '$', color: '#22c55e' },
  standard: { label: '$$', color: '#3b82f6' },
  premium: { label: '$$$', color: '#f59e0b' },
  ultra: { label: '$$$$', color: '#ef4444' },
};

export function getVideoProviders(excludeAliases = true): ProviderCatalogEntry[] {
  if (!excludeAliases) return VIDEO_PROVIDER_CATALOG;
  return VIDEO_PROVIDER_CATALOG.filter(p => !p.name.includes('Alias'));
}

export function getImageProviders(): ProviderCatalogEntry[] {
  return IMAGE_PROVIDER_CATALOG;
}
