export interface PiAPITestDefinition {
  id: string;
  name: string;
  category: 'video' | 'image' | 'audio' | 'llm' | 'llm-service' | 'i2v' | 'i2i' | 'v2v' | 'toolkit' | 'character-performance' | 'talking-photo';
  model: string;
  taskType: string;
  input: Record<string, any>;
  config?: Record<string, any>;
  endpoint?: string;
  pollEndpoint?: string;
  pollForResult: boolean;
  estimatedCost: string;
  estimatedTime: string;
  timeoutMs?: number;
  notes?: string;
  requiresImage?: boolean;
  imageInputField?: string;
  requiresVideo?: boolean;
  videoInputField?: string;
  requiresAudio?: boolean;
  audioInputField?: string;
  disabled?: boolean;
  disabledReason?: string;
}

export const PIAPI_TEST_DEFINITIONS: PiAPITestDefinition[] = [
  // ==================== VIDEO GENERATION (T2V) ====================
  {
    id: 'kling-2.6',
    name: 'Kling 2.6',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'A gentle breeze moves through tall grass in golden sunlight',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.6',
    },
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
  },
  {
    id: 'kling-3.0-omni',
    name: 'Kling 3.0 Omni',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'A calm river flowing through autumn forest',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '3.0',
    },
    pollForResult: true,
    estimatedCost: '$0.21',
    estimatedTime: '~90s',
  },
  {
    id: 'kling-2.5',
    name: 'Kling 2.5',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'Soft clouds drifting across a blue sky',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.5',
    },
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
  },
  {
    id: 'hailuo',
    name: 'Hailuo',
    category: 'video',
    model: 'hailuo',
    taskType: 'video_generation',
    input: {
      prompt: 'Ocean waves gently rolling onto a sandy beach at sunset',
      model: 'v2.3',
      expand_prompt: true,
      duration: 6,
      resolution: 768,
    },
    config: {
      service_mode: 'public',
    },
    pollForResult: true,
    estimatedCost: '$0.20',
    estimatedTime: '~120s',
  },
  {
    id: 'hunyuan',
    name: 'Hunyuan',
    category: 'video',
    model: 'Qubico/hunyuan',
    taskType: 'txt2video',
    input: {
      prompt: 'A butterfly landing on a flower in slow motion',
    },
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~300s',
    timeoutMs: 360000,
  },
  {
    id: 'luma',
    name: 'Luma',
    category: 'video',
    model: 'luma',
    taskType: 'video_generation',
    input: {
      model: 'ray-v2',
      prompt: 'Morning mist rising over a quiet lake surrounded by mountains',
      duration: 5,
      aspect_ratio: '16:9',
      loop: false,
    },
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~90s',
  },
  {
    id: 'wan-2.6',
    name: 'Wan 2.6',
    category: 'video',
    model: 'Wan',
    taskType: 'wan26-txt2video',
    input: {
      prompt: 'A field of wildflowers swaying in a gentle wind',
      negative_prompt: 'low resolution, blurry',
      prompt_extend: true,
      resolution: '720p',
      aspect_ratio: '16:9',
      duration: 5,
      watermark: false,
    },
    pollForResult: true,
    estimatedCost: '$0.15',
    estimatedTime: '~90s',
  },
  {
    id: 'wan-2.2',
    name: 'Wan 2.2',
    category: 'video',
    model: 'Qubico/wanx',
    taskType: 'wan22-txt2video-14b',
    input: {
      prompt: 'Rain drops falling on a window pane',
    },
    pollForResult: true,
    estimatedCost: '$0.28',
    estimatedTime: '~600s',
    timeoutMs: 660000,
  },
  {
    id: 'wan-2.1',
    name: 'Wan 2.1',
    category: 'video',
    model: 'Qubico/wanx',
    taskType: 'txt2video-14b',
    input: {
      prompt: 'A candle flame flickering in darkness',
    },
    pollForResult: true,
    estimatedCost: '$0.28',
    estimatedTime: '~600s',
    timeoutMs: 660000,
  },
  {
    id: 'seedance-2',
    name: 'Seedance 2',
    category: 'video',
    model: 'seedance',
    taskType: 'seedance-2',
    input: {
      prompt: 'A golden retriever runs through a sunlit meadow with wildflowers',
      mode: 'text_to_video',
      duration: 5,
      aspect_ratio: '16:9',
    },
    pollForResult: true,
    estimatedCost: '$0.75',
    estimatedTime: '~25 min',
    timeoutMs: 1800000,
  },
  {
    id: 'seedance-2-fast',
    name: 'Seedance 2 Fast',
    category: 'video',
    model: 'seedance',
    taskType: 'seedance-2-fast',
    input: {
      prompt: 'Snow falling gently on pine trees in a winter forest',
      mode: 'text_to_video',
      duration: 5,
      aspect_ratio: '16:9',
    },
    timeoutMs: 1800000,
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~15 min',
  },
  {
    id: 'veo-3',
    name: 'Veo 3',
    category: 'video',
    model: 'veo3',
    taskType: 'veo3-video-fast',
    input: {
      prompt: 'A peaceful garden with koi fish swimming in a clear pond',
      aspect_ratio: '16:9',
      duration: '4s',
      resolution: '720p',
    },
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~120s',
  },
  {
    id: 'veo-3.1',
    name: 'Veo 3.1',
    category: 'video',
    model: 'veo3.1',
    taskType: 'veo3.1-video-fast',
    input: {
      prompt: 'Leaves floating down a stream in autumn forest',
      aspect_ratio: '16:9',
      duration: '4s',
      resolution: '720p',
    },
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~120s',
  },
  {
    id: 'runway-4.5',
    name: 'Runway 4.5',
    category: 'video',
    model: 'runway',
    taskType: 'runway-direct',
    input: {
      prompt: 'A cinematic slow-motion shot of rain falling on a city street at night with neon reflections',
      duration: 5,
      aspect_ratio: '16:9',
    },
    endpoint: '/api/runway-tests/generate',
    pollEndpoint: '/api/runway-tests/poll',
    pollForResult: true,
    estimatedCost: '$0.35',
    estimatedTime: '~120s',
    notes: 'Direct Runway API — requires RUNWAY_API_KEY',
  },
  {
    id: 'runway-gen4',
    name: 'Runway Gen-4',
    category: 'video',
    model: 'runway',
    taskType: 'runway-direct',
    input: {
      prompt: 'A time-lapse of clouds moving over a mountain landscape at golden hour',
      duration: 5,
      aspect_ratio: '16:9',
    },
    endpoint: '/api/runway-tests/generate',
    pollEndpoint: '/api/runway-tests/poll',
    pollForResult: true,
    estimatedCost: '$0.25',
    estimatedTime: '~120s',
    notes: 'Direct Runway API — requires RUNWAY_API_KEY',
  },
  {
    id: 'runway-gen4-aleph',
    name: 'Runway Gen-4 Aleph',
    category: 'video',
    model: 'runway',
    taskType: 'runway-direct',
    input: {
      prompt: 'A dramatic aerial shot sweeping over a fog-covered forest at dawn',
      duration: 5,
      aspect_ratio: '16:9',
    },
    endpoint: '/api/runway-tests/generate',
    pollEndpoint: '/api/runway-tests/poll',
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~120s',
    notes: 'Direct Runway API — requires RUNWAY_API_KEY',
  },
  {
    id: 'runway-act-two',
    name: 'Runway Act Two',
    category: 'video',
    model: 'runway',
    taskType: 'runway-direct',
    input: {
      prompt: 'A person expressing joy and surprise, turning to face the camera with a warm smile',
      duration: 5,
      aspect_ratio: '16:9',
    },
    endpoint: '/api/runway-tests/generate',
    pollEndpoint: '/api/runway-tests/poll',
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~120s',
    notes: 'Direct Runway API — character performance specialization — requires RUNWAY_API_KEY',
  },
  {
    id: 'runway-happy-horse-1',
    name: 'Runway Happy Horse 1.0',
    category: 'video',
    model: 'runway',
    taskType: 'runway-direct',
    input: {
      prompt: 'A whimsical close-up of a horse galloping through a field of sunflowers at golden hour, creative stylized motion',
      duration: 5,
      aspect_ratio: '16:9',
    },
    endpoint: '/api/runway-tests/generate',
    pollEndpoint: '/api/runway-tests/poll',
    pollForResult: true,
    estimatedCost: '$0.40',
    estimatedTime: '~120s',
    notes: 'Direct Runway API — creative native model — requires RUNWAY_API_KEY',
  },
  {
    id: 'runway-agent-2',
    name: 'Runway Agent 2.0',
    category: 'video',
    model: 'runway',
    taskType: 'runway-direct',
    input: {
      prompt: 'Create a cinematic product showcase video: a sleek coffee mug sits on a marble countertop with steam rising, morning light, professional ad style',
      duration: 5,
      aspect_ratio: '16:9',
    },
    endpoint: '/api/runway-tests/generate',
    pollEndpoint: '/api/runway-tests/poll',
    pollForResult: true,
    timeoutMs: 360000,
    estimatedCost: '$0.50',
    estimatedTime: '~180s',
    notes: 'Direct Runway API — agentic video builder — requires RUNWAY_API_KEY',
  },
  {
    id: 'sora-2',
    name: 'Sora 2',
    category: 'video',
    model: 'sora2',
    taskType: 'sora2-video',
    input: {
      prompt: 'A paper airplane gliding through a sunlit room',
      aspect_ratio: '16:9',
      duration: 4,
    },
    pollForResult: true,
    estimatedCost: '$0.40',
    estimatedTime: '~120s',
  },
  {
    id: 'sora-2-pro',
    name: 'Sora 2 Pro',
    category: 'video',
    model: 'sora2',
    taskType: 'sora2-pro-video',
    input: {
      prompt: 'A cinematic tracking shot through a misty ancient forest at dawn',
      aspect_ratio: '16:9',
      resolution: '720p',
      duration: 4,
    },
    pollForResult: true,
    estimatedCost: '$0.60',
    estimatedTime: '~180s',
  },
  {
    id: 'omnihuman-1.5',
    name: 'OmniHuman 1.5',
    category: 'i2v',
    model: 'omni-human',
    taskType: 'omni-human-1.5',
    input: {
      prompt: 'A person speaks warmly and expressively with natural head movement',
      fast_mode: true,
    },
    requiresImage: true,
    imageInputField: 'image_url',
    requiresAudio: true,
    audioInputField: 'audio_url',
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~120s',
    notes: 'Talking photo: animates a portrait image to lip-sync with the provided audio. Upload a portrait photo and a speech audio clip.',
  },
  {
    id: 'kling-effects',
    name: 'Kling Effects (VFX)',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'Explosion of golden sparks and light trails emanating from a central point, cinematic VFX',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.6',
      effect_scene: 'sparkle',
    },
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
    notes: 'Kling VFX-specialized generation with effect_scene parameter',
  },
  {
    id: 'kling-avatar',
    name: 'Kling AI Avatar',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'A professional presenter speaking to camera',
      mode: 'std',
      duration: 5,
    },
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~90s',
    notes: 'Avatar mode - may require reference image',
  },
  {
    id: 'omniavatar',
    name: 'OmniAvatar',
    category: 'video',
    model: 'omniavatar',
    taskType: 'video_generation',
    input: {
      prompt: 'A digital avatar introducing themselves',
    },
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~120s',
    notes: 'Avatar generation - may require reference image',
  },

  // ==================== IMAGE-TO-VIDEO (I2V) ====================
  {
    id: 'i2v-kling-avatar',
    name: 'Kling AI Avatar I2V',
    category: 'i2v',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'A professional presenter speaks warmly and naturally to the camera',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.0',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.23',
    estimatedTime: '~90s',
    notes: 'Kling Avatar I2V: animates a portrait photo as an avatar. Uses version 2.0 avatar mode.',
  },
  {
    id: 'i2v-omniavatar',
    name: 'OmniAvatar I2V',
    category: 'i2v',
    model: 'omniavatar',
    taskType: 'video_generation',
    input: {
      prompt: 'A digital avatar speaks expressively with natural head movement',
      aspect_ratio: '16:9',
      duration: 5,
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~120s',
    notes: 'OmniAvatar I2V: animates a portrait image into a speaking avatar clip.',
  },
  {
    id: 'i2v-kling-2.6',
    name: 'Kling 2.6 I2V',
    category: 'i2v',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'The logo gently rotates with soft lighting, cinematic movement',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.6',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
  },
  {
    id: 'i2v-kling-2.5',
    name: 'Kling 2.5 I2V',
    category: 'i2v',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'Smooth zoom out revealing the full image with ambient particles',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.5',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
  },
  {
    id: 'i2v-hailuo',
    name: 'Hailuo I2V',
    category: 'i2v',
    model: 'hailuo',
    taskType: 'video_generation',
    input: {
      prompt: 'The image comes to life with gentle motion and natural movement',
      model: 'v2.3',
      duration: 6,
      resolution: 768,
    },
    config: {
      service_mode: 'public',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.20',
    estimatedTime: '~120s',
  },
  {
    id: 'i2v-hailuo-director',
    name: 'Hailuo Director I2V',
    category: 'i2v',
    model: 'hailuo',
    taskType: 'video_generation',
    input: {
      prompt: '[Push in,Pan left]smooth cinematic reveal',
      model: 'v2.3',
      duration: 6,
      resolution: 768,
    },
    config: {
      service_mode: 'public',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.20',
    estimatedTime: '~120s',
    notes: 'Camera control mode with directorial movements',
  },
  {
    id: 'i2v-wan-2.6',
    name: 'Wan 2.6 I2V',
    category: 'i2v',
    model: 'Wan',
    taskType: 'wan26-img2video',
    input: {
      prompt: 'The image animates with gentle movement and flowing energy',
      resolution: '720P',
      duration: 5,
      watermark: false,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.40',
    estimatedTime: '~90s',
  },
  {
    id: 'i2v-luma',
    name: 'Luma I2V',
    category: 'i2v',
    model: 'luma',
    taskType: 'video_generation',
    input: {
      model: 'ray-v2',
      prompt: 'Cinematic slow push in with subtle parallax depth effect',
      duration: 5,
      aspect_ratio: '16:9',
      loop: false,
    },
    pollEndpoint: '/api/luma/v1/video',
    requiresImage: true,
    imageInputField: 'start_image',
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~90s',
  },
  {
    id: 'i2v-veo-3',
    name: 'Veo 3 I2V',
    category: 'i2v',
    model: 'veo3',
    taskType: 'veo3-video-fast',
    input: {
      prompt: 'The image transforms into a cinematic scene with natural motion',
      aspect_ratio: '16:9',
      duration: '4s',
      resolution: '720p',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~120s',
  },
  {
    id: 'i2v-veo-3.1',
    name: 'Veo 3.1 I2V',
    category: 'i2v',
    model: 'veo3.1',
    taskType: 'veo3.1-video-fast',
    input: {
      prompt: 'Smooth animation of the image with professional camera movement',
      aspect_ratio: '16:9',
      duration: '4s',
      resolution: '720p',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~120s',
  },
  {
    id: 'i2v-seedance-2',
    name: 'Seedance 2 I2V',
    category: 'i2v',
    model: 'seedance',
    taskType: 'seedance-2',
    input: {
      prompt: 'The cat in @image1 walks through a garden',
      mode: 'image_to_video',
      duration: 5,
      aspect_ratio: '16:9',
    },
    requiresImage: true,
    imageInputField: 'image_urls',
    pollForResult: true,
    estimatedCost: '$0.75',
    estimatedTime: '~25 min',
    timeoutMs: 1800000,
  },
  {
    id: 'i2v-seedance-2-fast',
    name: 'Seedance 2 Fast I2V',
    category: 'i2v',
    model: 'seedance',
    taskType: 'seedance-2-fast',
    input: {
      prompt: 'The subject in @image1 moves with gentle flowing motion',
      mode: 'image_to_video',
      duration: 5,
      aspect_ratio: '16:9',
    },
    requiresImage: true,
    imageInputField: 'image_urls',
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~15 min',
    timeoutMs: 1800000,
  },
  {
    id: 'i2v-seedance-2-first-last-frames',
    name: 'Seedance 2 First-Last Frames (Seamless Transitions)',
    category: 'i2v',
    model: 'seedance',
    taskType: 'seedance-2-fast',
    input: {
      prompt: 'Smooth continuous motion: subject transitions naturally, lighting and environment flow seamlessly',
      mode: 'first_last_frames',
      duration: 5,
      aspect_ratio: 'auto',
    },
    requiresImage: true,
    imageInputField: 'image_urls',
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~15 min',
    timeoutMs: 1800000,
    notes: 'Native Seedance 2 continuity mode. image_urls accepts 1–2 images: [firstFrame] locks the start, or [firstFrame, lastFrame] locks both ends. aspect_ratio must be "auto" in this mode. Used by Cinematic Flow / Seamless Transitions to chain scenes.',
  },
  {
    id: 'i2v-skyreels',
    name: 'Skyreels I2V',
    category: 'i2v',
    model: 'Qubico/skyreels',
    taskType: 'img2video',
    input: {
      prompt: 'FPS-24, gentle movement and natural motion of the subject',
      negative_prompt: 'chaotic, distortion, morphing',
      aspect_ratio: '16:9',
      guidance_scale: 3.5,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~90s',
  },

  // ==================== IMAGE-TO-IMAGE (I2I) ====================
  {
    id: 'i2i-flux-schnell',
    name: 'Flux Schnell I2I',
    category: 'i2i',
    model: 'Qubico/flux1-schnell',
    taskType: 'img2img',
    input: {
      prompt: 'Transform into a vibrant watercolor painting style, keep the composition',
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.01',
    estimatedTime: '~5s',
  },
  {
    id: 'i2i-flux-dev',
    name: 'Flux Dev I2I',
    category: 'i2i',
    model: 'Qubico/flux1-dev',
    taskType: 'img2img',
    input: {
      prompt: 'Reimagine as a 3D rendered scene with soft studio lighting',
      width: 1024,
      height: 1024,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.015',
    estimatedTime: '~10s',
  },
  {
    id: 'i2i-seedream',
    name: 'Seedream 4.0 I2I',
    category: 'i2i',
    model: 'bytedance/seedream-v4.0',
    taskType: 'img2img',
    input: {
      prompt: 'Transform into a luxury brand advertisement style with golden accents',
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~8s',
    disabled: true,
    disabledReason: 'Seedream requires direct API access - not available via PiAPI',
  },
  {
    id: 'i2i-qwen',
    name: 'Qwen Image I2I',
    category: 'i2i',
    model: 'Qubico/qwen-image',
    taskType: 'image-edit',
    input: {
      prompt: 'Redraw in traditional Japanese ink wash painting style',
      negative_prompt: '',
      seed: -1,
      steps: 8,
      flow_shift: 3,
    },
    requiresImage: true,
    imageInputField: 'image1',
    pollForResult: true,
    estimatedCost: '$0.075',
    estimatedTime: '~10s',
  },

  // ==================== IMAGE GENERATION (T2I) ====================
  {
    id: 'flux-schnell',
    name: 'Flux Schnell',
    category: 'image',
    model: 'Qubico/flux1-schnell',
    taskType: 'txt2img',
    input: {
      prompt: 'A serene Japanese garden with cherry blossoms, koi pond, stone lantern, watercolor style',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.003',
    estimatedTime: '~5s',
  },
  {
    id: 'flux-dev',
    name: 'Flux Dev',
    category: 'image',
    model: 'Qubico/flux1-dev',
    taskType: 'txt2img',
    input: {
      prompt: 'A cozy cabin in the woods with warm light glowing from windows at twilight',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.015',
    estimatedTime: '~10s',
  },
  {
    id: 'flux-dev-advanced',
    name: 'Flux Dev Advanced',
    category: 'image',
    model: 'Qubico/flux1-dev-advanced',
    taskType: 'txt2img',
    input: {
      prompt: 'Professional product photography of a ceramic coffee mug on a marble countertop, soft natural light',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~10s',
    disabled: true,
    disabledReason: 'Qubico/flux1-dev-advanced returns invalid model error - may not be available on PiAPI yet',
  },
  {
    id: 'ideogram-v2',
    name: 'Ideogram V2',
    category: 'image',
    model: 'Qubico/ideogram-v2',
    taskType: 'txt2img',
    input: {
      prompt: 'A professional book cover design with the title "THE WEIGHT LOSS ILLUSION" in elegant gold serif typography on a dark navy background, subtle geometric patterns, premium editorial design, clean readable text',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.05',
    estimatedTime: '~15s',
    notes: 'Ideogram V2 via PiAPI - excellent at rendering readable text in images',
    disabled: true,
    disabledReason: 'Ideogram V2 not available on PiAPI - both Qubico/ideogram-v2 and ideogram-v2 model IDs return HTTP 400. TODO: Get API key directly from Ideogram (ideogram.ai) for direct integration. Use GPT-Image-1 (OpenAI Direct) for text rendering in the meantime.',
  },
  {
    id: 'gpt-image-1',
    name: 'GPT-Image-1 (OpenAI Direct)',
    category: 'image',
    model: 'gpt-image-1',
    taskType: 'txt2img',
    input: {
      prompt: 'A cinematic chapter title card design: elegant text reading "Chapter 1: The Weight Loss Illusion" centered on a dark moody background with soft golden light rays, professional documentary style, clean readable typography',
    },
    endpoint: 'openai-direct',
    pollForResult: false,
    estimatedCost: '$0.04',
    estimatedTime: '~15s',
    notes: 'Uses OpenAI API directly (OPENAI_API_KEY) - best text rendering quality',
  },
  {
    id: 'gpt-image-1-piapi',
    name: 'GPT-Image-1 (PiAPI)',
    category: 'image',
    model: 'gpt-4o-image',
    taskType: 'txt2img',
    input: {
      prompt: 'A whimsical illustration of a fox reading a book under a tree',
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.04',
    estimatedTime: '~15s',
    notes: 'Uses PiAPI chat completions endpoint',
    disabled: true,
    disabledReason: 'GPT-Image-1 not available on PiAPI - use OpenAI Direct version instead',
  },
  {
    id: 'gpt-image-1.5',
    name: 'GPT Image 1.5',
    category: 'image',
    model: 'gpt-image-1.5',
    taskType: 'txt2img',
    input: {
      prompt: 'A minimalist logo design of a mountain with sunrise, clean vector style',
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.05',
    estimatedTime: '~15s',
    notes: 'Uses chat completions endpoint',
    disabled: true,
    disabledReason: 'GPT-Image-1.5 not available on PiAPI - not listed in PiAPI documentation',
  },
  {
    id: 'qwen-image',
    name: 'Qwen Image',
    category: 'image',
    model: 'Qubico/qwen-image',
    taskType: 'txt2img',
    input: {
      prompt: 'An elegant calligraphy brush painting of bamboo with a red seal stamp',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.075',
    estimatedTime: '~10s',
  },
  {
    id: 'nano-banana',
    name: 'Nano Banana (Gemini 2.5 Flash)',
    category: 'image',
    model: 'gemini',
    taskType: 'gemini-2.5-flash-image',
    input: {
      prompt: 'A photorealistic still life of fresh fruits in a wooden bowl, natural window light',
      output_format: 'png',
      aspect_ratio: '1:1',
    },
    pollForResult: true,
    estimatedCost: '$0.03',
    estimatedTime: '~5s',
  },
  {
    id: 'nano-banana-pro',
    name: 'Nano Banana Pro',
    category: 'image',
    model: 'gemini',
    taskType: 'nano-banana-pro',
    input: {
      prompt: 'Luxury perfume bottle on black marble surface, dramatic studio lighting, product photography',
      output_format: 'png',
      aspect_ratio: '1:1',
    },
    pollForResult: true,
    estimatedCost: '$0.105',
    estimatedTime: '~8s',
  },
  {
    id: 'nano-banana-2',
    name: 'Nano Banana 2 (Gemini 3.1 Flash)',
    category: 'image',
    model: 'gemini',
    taskType: 'gemini-2.5-flash-image',
    input: {
      prompt: 'A sophisticated woman holding a premium supplement bottle in a sunlit modern kitchen, cinematic lighting, photorealistic',
      output_format: 'jpeg',
      aspect_ratio: '16:9',
    },
    pollForResult: true,
    estimatedCost: '$0.03',
    estimatedTime: '~5-25s',
    notes: 'Nano Banana 2 — Gemini 3.1 Flash Image. Fast, photorealistic T2I with 4K support and up to 14 reference images.',
  },
  {
    id: 'nano-banana-2-multi',
    name: 'Nano Banana 2 Multi (4 images)',
    category: 'image',
    model: 'gemini',
    taskType: 'gemini-2.5-flash-image',
    input: {
      prompt: 'A golden retriever puppy sitting in a field of wildflowers at golden hour, soft bokeh background, professional pet photography',
      output_format: 'jpeg',
      aspect_ratio: '1:1',
      num_images: 4,
    },
    pollForResult: true,
    estimatedCost: '$0.12',
    estimatedTime: '~10-30s',
    notes: 'Nano Banana 2 multi-image generation — 4 candidates in a single request for batch workflows.',
  },
  {
    id: 'seedream-4.0',
    name: 'Seedream 4.0',
    category: 'image',
    model: 'bytedance/seedream-v4.0',
    taskType: 'txt2img',
    input: {
      prompt: 'A majestic eagle soaring above snow-capped mountains at golden hour, cinematic',
    },
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~8s',
    disabled: true,
    disabledReason: 'Seedream requires direct API access - not available via PiAPI',
  },
  {
    id: 'z-image-turbo',
    name: 'Z Image Turbo',
    category: 'image',
    model: 'Qubico/z-image',
    taskType: 'txt2img',
    input: {
      prompt: 'Modern minimalist interior design living room with large windows and natural light',
      negative_prompt: 'blurry',
      width: 1024,
      height: 1024,
      batch_size: 1,
    },
    pollForResult: true,
    estimatedCost: '$0.01',
    estimatedTime: '~3s',
  },

  // ==================== RECRAFT IMAGE GENERATION (Direct API) ====================
  {
    id: 'recraft-v4',
    name: 'Recraft V4',
    category: 'image',
    model: 'recraftv4',
    taskType: 'txt2img',
    endpoint: 'recraft-direct',
    input: {
      prompt: 'A warm sunlit modern kitchen with marble countertops, fresh vegetables in a wooden bowl, natural light through large windows',
      model: 'recraftv4',
      aspect_ratio: '16:9',
    },
    pollForResult: false,
    estimatedCost: '$0.04',
    estimatedTime: '~10s',
  },
  {
    id: 'recraft-v4-pro',
    name: 'Recraft V4 Pro (4MP)',
    category: 'image',
    model: 'recraftv4_pro',
    taskType: 'txt2img',
    endpoint: 'recraft-direct',
    input: {
      prompt: 'Cinematic wide shot of a mountain valley at golden hour, mist rising from the river, dramatic clouds',
      model: 'recraftv4_pro',
      aspect_ratio: '16:9',
    },
    pollForResult: false,
    estimatedCost: '$0.08',
    estimatedTime: '~15s',
  },
  {
    id: 'recraft-v3-text',
    name: 'Recraft V3 (Branded Text)',
    category: 'image',
    model: 'recraftv3',
    taskType: 'txt2img',
    endpoint: 'recraft-direct',
    input: {
      prompt: 'A rustic wooden building with a porch, rolling green hills in the background, warm afternoon light. The text "PINE HILL FARM" appears on a sign above the entrance.',
      model: 'recraftv3',
      style: 'realistic_image',
      aspect_ratio: '16:9',
    },
    pollForResult: false,
    estimatedCost: '$0.04',
    estimatedTime: '~10s',
  },

  // ==================== AUDIO GENERATION ====================
  {
    id: 'diffrhythm',
    name: 'DiffRhythm',
    category: 'audio',
    model: 'Qubico/diffrhythm',
    taskType: 'txt2audio-base',
    input: {
      lyrics: '[verse]\nGentle morning light\nSoft breeze through the trees\n[chorus]\nNature sings along\nPeaceful melody',
      style_prompt: 'ambient calm instrumental',
    },
    pollForResult: true,
    estimatedCost: '$0.05',
    estimatedTime: '~30s',
  },
  {
    id: 'udio',
    name: 'Udio',
    category: 'audio',
    model: 'music-u',
    taskType: 'generate_music',
    input: {
      gpt_description_prompt: 'calm ambient piano music, gentle and relaxing, nature sounds',
      negative_tags: 'aggressive loud distorted',
      lyrics_type: 'instrumental',
      seed: -1,
    },
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~60s',
  },
  {
    id: 'f5-tts',
    name: 'F5 TTS',
    category: 'audio',
    model: 'Qubico/tts',
    taskType: 'zero-shot',
    input: {
      gen_text: 'Welcome to the AI Video Production Studio. This is a test of the text to speech system.',
      ref_audio: '',
      ref_text: '',
    },
    pollForResult: true,
    estimatedCost: '$0.025',
    estimatedTime: '~10s',
    notes: 'Requires ref_audio for voice cloning, or uses default voice',
  },
  {
    id: 'mmaudio',
    name: 'MMAudio',
    category: 'audio',
    model: 'Qubico/mmaudio',
    taskType: 'video2audio',
    input: {
      prompt: 'gentle nature sounds, birds chirping, wind rustling leaves',
      negative_prompt: 'loud noise music speech',
      video: '',
      steps: 20,
      seed: 48511119825268,
    },
    pollForResult: true,
    estimatedCost: '$0.03',
    estimatedTime: '~15s',
    notes: 'Video-to-audio generation - requires video URL input',
    disabled: true,
    disabledReason: 'Requires video URL input - video upload for audio tests not yet implemented',
  },
  {
    id: 'ace-step',
    name: 'ACE Step AI',
    category: 'audio',
    model: 'Qubico/ace-step',
    taskType: 'text2audio',
    input: {
      lyrics: '[inst]',
      style_prompt: 'soft ambient electronic chill',
      negative_prompt: 'noise distortion',
    },
    pollForResult: true,
    estimatedCost: '$0.05',
    estimatedTime: '~30s',
  },
  {
    id: 'moshi',
    name: 'Moshi',
    category: 'audio',
    model: 'moshi',
    taskType: 'conversation',
    input: {
      prompt: 'Hello, can you hear me?',
    },
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~10s',
    notes: 'Conversational AI - may be on waitlist',
  },

  // ==================== LLM ====================
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'llm',
    model: 'deepseek-chat',
    taskType: 'chat-completion',
    input: {
      messages: [
        { role: 'user', content: 'Respond with exactly: "PiAPI DeepSeek test successful"' },
      ],
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.001',
    estimatedTime: '~3s',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    category: 'llm',
    model: 'gpt-4o',
    taskType: 'chat-completion',
    input: {
      messages: [
        { role: 'user', content: 'Respond with exactly: "PiAPI GPT-4o test successful"' },
      ],
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.005',
    estimatedTime: '~3s',
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'llm',
    model: 'claude-sonnet-4-6',
    taskType: 'chat-completion',
    input: {
      messages: [
        { role: 'user', content: 'Respond with exactly: "PiAPI Claude test successful"' },
      ],
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.003',
    estimatedTime: '~3s',
  },
  {
    id: 'deep-research',
    name: 'Deep Research',
    category: 'llm',
    model: 'deep-research',
    taskType: 'chat-completion',
    input: {
      messages: [
        { role: 'user', content: 'What is 2+2? Answer briefly.' },
      ],
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.01',
    estimatedTime: '~10s',
    notes: 'Deep research model - may take longer',
  },

  // ==================== LLM SERVICE INTEGRATION (piapi-llm-client) ====================
  {
    id: 'llm-script-generation',
    name: 'Script Generation',
    category: 'llm-service',
    model: 'piapi-llm-client',
    taskType: 'llm-service-test',
    input: {
      serviceId: 'script-generation',
      systemPrompt: 'You are a video script writer. Generate a 2-scene marketing video script for the product described. Return JSON with scenes array, each with type, narration, and visualDirection.',
      userMessage: 'Create a short script for a natural skincare brand launching a new moisturizer. Just 2 scenes: hook and product reveal.',
    },
    endpoint: 'llm-service',
    pollForResult: false,
    estimatedCost: '$0.003',
    estimatedTime: '~5s',
    notes: 'Tests piapi-llm-client (PiAPI → Anthropic failover) for script generation',
  },
  {
    id: 'llm-visual-direction',
    name: 'Visual Direction',
    category: 'llm-service',
    model: 'piapi-llm-client',
    taskType: 'llm-service-test',
    input: {
      serviceId: 'visual-direction',
      systemPrompt: 'You are a visual director for AI video production. Create a detailed visual direction for a video scene that can be used as an AI generation prompt.',
      userMessage: 'Scene type: hook. Narration: "Are you tired of using harsh chemicals on your skin?" Art style: 3D Illustration / Pixar style. Write a visual direction.',
    },
    endpoint: 'llm-service',
    pollForResult: false,
    estimatedCost: '$0.003',
    estimatedTime: '~5s',
    notes: 'Tests piapi-llm-client for visual direction / prompt generation',
  },
  {
    id: 'llm-prompt-improvement',
    name: 'Prompt Enhancement',
    category: 'llm-service',
    model: 'piapi-llm-client',
    taskType: 'llm-service-test',
    input: {
      serviceId: 'prompt-improvement',
      systemPrompt: 'You are an AI video prompt optimizer. Improve the given visual direction to be more specific, cinematic, and optimized for AI video generation. Return the improved prompt only.',
      userMessage: 'Improve this prompt: "A woman using skincare products in a bathroom"',
    },
    endpoint: 'llm-service',
    pollForResult: false,
    estimatedCost: '$0.002',
    estimatedTime: '~4s',
    notes: 'Tests piapi-llm-client for intelligent prompt improvement',
  },
  {
    id: 'llm-provider-selection',
    name: 'Provider Selection',
    category: 'llm-service',
    model: 'piapi-llm-client',
    taskType: 'llm-service-test',
    input: {
      serviceId: 'provider-selection',
      systemPrompt: 'You are an AI video provider selection expert. Given a scene description, recommend the best AI video provider. Return JSON with providerId and reasoning.',
      userMessage: 'Scene: A close-up product reveal of a glass jar with cream, slow camera orbit, warm studio lighting, photorealistic style. Which provider should I use?',
    },
    endpoint: 'llm-service',
    pollForResult: false,
    estimatedCost: '$0.002',
    estimatedTime: '~4s',
    notes: 'Tests piapi-llm-client for intelligent provider selection',
  },
  {
    id: 'llm-text-labels',
    name: 'Text Label Extraction',
    category: 'llm-service',
    model: 'piapi-llm-client',
    taskType: 'llm-service-test',
    input: {
      serviceId: 'text-labels',
      systemPrompt: 'You are a text label extractor for video production. Extract 2-3 key terms from the narration that should appear as on-screen text labels. Return JSON with labels array.',
      userMessage: 'Narration: "Our organic CBD moisturizer contains 500mg of full-spectrum hemp extract and organic shea butter for deep hydration."',
    },
    endpoint: 'llm-service',
    pollForResult: false,
    estimatedCost: '$0.001',
    estimatedTime: '~3s',
    notes: 'Tests piapi-llm-client for text label extraction from narrations',
  },
  {
    id: 'llm-ask-suzzie',
    name: 'Ask Suzzie Assistant',
    category: 'llm-service',
    model: 'piapi-llm-client',
    taskType: 'llm-service-test',
    input: {
      serviceId: 'ask-suzzie',
      systemPrompt: 'You are Suzzie, a friendly AI creative assistant for a video production platform. Help users with visual directions, provider recommendations, and platform features.',
      userMessage: 'Which AI provider would be best for a 3D illustration Pixar-style scene showing a character applying skincare?',
    },
    endpoint: 'llm-service',
    pollForResult: false,
    estimatedCost: '$0.003',
    estimatedTime: '~5s',
    notes: 'Tests piapi-llm-client for the Ask Suzzie conversational assistant',
  },

  // ==================== VIDEO-TO-VIDEO (V2V) ====================
  {
    id: 'v2v-runway-gen4-aleph',
    name: 'Runway Gen-4 Aleph V2V',
    category: 'v2v',
    model: 'runway',
    taskType: 'runway-direct-v2v',
    input: {
      prompt: 'Transform this video into a dreamlike cinematic sequence with soft color grading and ethereal lighting',
      duration: 5,
      aspect_ratio: '16:9',
    },
    requiresVideo: true,
    videoInputField: 'video_url',
    pollForResult: true,
    estimatedCost: '$0.35',
    estimatedTime: '~180s',
    notes: 'Direct Runway API — prompt-based video transformation with gen4_aleph model',
  },
  {
    id: 'v2v-runway-aleph-2',
    name: 'Runway Aleph 2.0',
    category: 'v2v',
    model: 'runway',
    taskType: 'runway-direct-v2v',
    input: {
      prompt: 'Transform this clip into a dark cinematic noir with deep shadows and high contrast blue and amber tones',
      duration: 5,
      aspect_ratio: '16:9',
    },
    requiresVideo: true,
    videoInputField: 'video_url',
    pollForResult: true,
    estimatedCost: '$0.45',
    estimatedTime: '~180s',
    notes: 'Direct Runway API — frame-based video editing (Aleph 2.0) — requires RUNWAY_API_KEY',
  },
  {
    id: 'v2v-kling-object-replace',
    name: 'Kling V2V Object Replace',
    category: 'v2v',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'Replace the main object with a golden statue, maintain motion and lighting',
      mode: 'std',
      version: '2.6',
    },
    requiresVideo: true,
    videoInputField: 'video_url',
    requiresImage: true,
    imageInputField: 'replacement_image_url',
    pollForResult: true,
    estimatedCost: '$0.20',
    estimatedTime: '~120s',
    notes: 'Kling object replacement — requires both source video and replacement image',
  },

  // ==================== TOOLKIT (Upscale / BG Removal) ====================
  {
    id: 'toolkit-upscale-image',
    name: 'Qubic Image Upscale',
    category: 'toolkit',
    model: 'Qubico/image-toolkit',
    taskType: 'upscale',
    input: {
      scale: 2,
      face_enhance: true,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~15s',
    notes: 'Upscales image by 2x or 4x using Qubic Image Toolkit',
  },
  {
    id: 'toolkit-upscale-video',
    name: 'Qubic Video Upscale',
    category: 'toolkit',
    model: 'Qubico/video-toolkit',
    taskType: 'upscale',
    input: {},
    requiresVideo: true,
    videoInputField: 'video',
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~10min',
    timeoutMs: 600000,
    notes: 'Upscales video using Qubic Video Toolkit — may take 6-10 minutes',
  },
  {
    id: 'toolkit-bg-remove-image',
    name: 'Qubic Image BG Removal',
    category: 'toolkit',
    model: 'Qubico/image-toolkit',
    taskType: 'background-remove',
    input: {
      rmbg_model: 'RMBG-2.0',
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.01',
    estimatedTime: '~10s',
    notes: 'Removes background from image using Qubic Image Toolkit with RMBG-2.0',
  },
  {
    id: 'toolkit-bg-remove-video',
    name: 'Qubic Video BG Removal',
    category: 'toolkit',
    model: 'Qubico/video-toolkit',
    taskType: 'background-remove',
    input: {
      invert_output: false,
    },
    requiresVideo: true,
    videoInputField: 'video',
    pollForResult: true,
    estimatedCost: '$0.08',
    estimatedTime: '~10min',
    timeoutMs: 600000,
    notes: 'Removes background from video using Qubic Video Toolkit — may take 6-10 minutes',
  },

  // ==================== CHARACTER PERFORMANCE ====================
  {
    id: 'cp-runway-act-two',
    name: 'Runway Act Two Character Performance',
    category: 'character-performance',
    model: 'runway',
    taskType: 'runway-direct-cp',
    input: {
      body_control: true,
    },
    requiresImage: true,
    imageInputField: 'character_image',
    requiresVideo: true,
    videoInputField: 'reference_video',
    pollForResult: true,
    estimatedCost: '$0.40',
    estimatedTime: '~180s',
    notes: 'Runway Act Two — animates a character image using motion from a reference performance video. Requires both a character image and a reference video.',
  },
];

export function getTestsByCategory(category: string): PiAPITestDefinition[] {
  return PIAPI_TEST_DEFINITIONS.filter(t => t.category === category);
}

export function getTestById(id: string): PiAPITestDefinition | undefined {
  return PIAPI_TEST_DEFINITIONS.find(t => t.id === id);
}
