export interface PiAPITestDefinition {
  id: string;
  name: string;
  category: 'video' | 'image' | 'audio' | 'llm' | 'i2v' | 'i2i';
  model: string;
  taskType: string;
  input: Record<string, any>;
  config?: Record<string, any>;
  endpoint?: string;
  pollForResult: boolean;
  estimatedCost: string;
  estimatedTime: string;
  notes?: string;
  requiresImage?: boolean;
  imageInputField?: string;
}

export const PIAPI_TEST_DEFINITIONS: PiAPITestDefinition[] = [
  // ==================== VIDEO GENERATION (T2V) ====================
  {
    id: 'kling-2.6',
    name: 'Kling 2.6',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'A gentle breeze moves through tall grass in golden sunlight',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.6',
    },
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
  },
  {
    id: 'kling-3.0-omni',
    name: 'Kling 3.0 Omni',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'A calm river flowing through autumn forest',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '3.0',
    },
    pollForResult: true,
    estimatedCost: '$0.21',
    estimatedTime: '~90s',
  },
  {
    id: 'kling-2.5',
    name: 'Kling 2.5',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'Soft clouds drifting across a blue sky',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.5',
    },
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
  },
  {
    id: 'hailuo',
    name: 'Hailuo',
    category: 'video',
    model: 'hailuo',
    taskType: 'video_generation',
    input: {
      prompt: 'Ocean waves gently rolling onto a sandy beach at sunset',
      model: 'v2.3',
      expand_prompt: true,
      duration: 6,
      resolution: 768,
    },
    config: {
      service_mode: 'public',
    },
    pollForResult: true,
    estimatedCost: '$0.20',
    estimatedTime: '~120s',
  },
  {
    id: 'hunyuan',
    name: 'Hunyuan',
    category: 'video',
    model: 'Qubico/hunyuan',
    taskType: 'txt2video',
    input: {
      prompt: 'A butterfly landing on a flower in slow motion',
    },
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~120s',
  },
  {
    id: 'luma',
    name: 'Luma',
    category: 'video',
    model: 'luma',
    taskType: 'video_generation',
    input: {
      prompt: 'Morning mist rising over a quiet lake surrounded by mountains',
      aspect_ratio: '16:9',
    },
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~90s',
  },
  {
    id: 'wan-2.6',
    name: 'Wan 2.6',
    category: 'video',
    model: 'wan',
    taskType: 'video_generation',
    input: {
      prompt: 'A field of wildflowers swaying in a gentle wind',
      version: '2.6',
    },
    pollForResult: true,
    estimatedCost: '$0.15',
    estimatedTime: '~90s',
  },
  {
    id: 'wan-2.5',
    name: 'Wan 2.5',
    category: 'video',
    model: 'wan',
    taskType: 'video_generation',
    input: {
      prompt: 'Sunlight streaming through forest canopy',
      version: '2.5',
    },
    pollForResult: true,
    estimatedCost: '$0.15',
    estimatedTime: '~90s',
  },
  {
    id: 'wan-2.2',
    name: 'Wan 2.2',
    category: 'video',
    model: 'wan',
    taskType: 'video_generation',
    input: {
      prompt: 'Rain drops falling on a window pane',
      version: '2.2',
    },
    pollForResult: true,
    estimatedCost: '$0.15',
    estimatedTime: '~90s',
  },
  {
    id: 'wan-2.1',
    name: 'Wan 2.1',
    category: 'video',
    model: 'wan',
    taskType: 'video_generation',
    input: {
      prompt: 'A candle flame flickering in darkness',
      version: '2.1',
    },
    pollForResult: true,
    estimatedCost: '$0.15',
    estimatedTime: '~90s',
  },
  {
    id: 'skyreels',
    name: 'Skyreels',
    category: 'video',
    model: 'skyreels',
    taskType: 'video_generation',
    input: {
      prompt: 'Stars twinkling in a clear night sky with milky way visible',
    },
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~60s',
  },
  {
    id: 'seedance-pro',
    name: 'Seedance 1.0 Pro',
    category: 'video',
    model: 'seedance',
    taskType: 'video_generation',
    input: {
      prompt: 'A hummingbird hovering near a tropical flower',
      version: '1.0-pro',
    },
    pollForResult: true,
    estimatedCost: '$0.25',
    estimatedTime: '~120s',
  },
  {
    id: 'seedance-lite',
    name: 'Seedance 1.0 Lite',
    category: 'video',
    model: 'seedance',
    taskType: 'video_generation',
    input: {
      prompt: 'Snow falling gently on pine trees',
      version: '1.0-lite',
    },
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~60s',
  },
  {
    id: 'veo-3',
    name: 'Veo 3',
    category: 'video',
    model: 'veo3',
    taskType: 'veo3-video-fast',
    input: {
      prompt: 'A peaceful garden with koi fish swimming in a clear pond',
      aspect_ratio: '16:9',
      duration: '4s',
      resolution: '720p',
    },
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~120s',
  },
  {
    id: 'veo-3.1',
    name: 'Veo 3.1',
    category: 'video',
    model: 'veo3.1',
    taskType: 'veo3.1-video-fast',
    input: {
      prompt: 'Leaves floating down a stream in autumn forest',
      aspect_ratio: '16:9',
      duration: '4s',
      resolution: '720p',
    },
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~120s',
  },
  {
    id: 'sora-2',
    name: 'Sora 2',
    category: 'video',
    model: 'sora2',
    taskType: 'sora2-text-to-video',
    input: {
      prompt: 'A paper airplane gliding through a sunlit room',
    },
    pollForResult: true,
    estimatedCost: '$0.40',
    estimatedTime: '~120s',
  },
  {
    id: 'omnihuman',
    name: 'OmniHuman',
    category: 'video',
    model: 'omnihuman',
    taskType: 'video_generation',
    input: {
      prompt: 'A person walking through a park on a sunny day',
    },
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~120s',
    notes: 'May require reference image for best results',
  },
  {
    id: 'omnihuman-1.5',
    name: 'OmniHuman 1.5',
    category: 'video',
    model: 'omnihuman',
    taskType: 'video_generation',
    input: {
      prompt: 'A person waving hello with a friendly smile',
      version: '1.5',
    },
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~120s',
    notes: 'May require reference image for best results',
  },
  {
    id: 'kling-avatar',
    name: 'Kling AI Avatar',
    category: 'video',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'A professional presenter speaking to camera',
      mode: 'std',
      duration: 5,
    },
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~90s',
    notes: 'Avatar mode - may require reference image',
  },
  {
    id: 'omniavatar',
    name: 'OmniAvatar',
    category: 'video',
    model: 'omniavatar',
    taskType: 'video_generation',
    input: {
      prompt: 'A digital avatar introducing themselves',
    },
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~120s',
    notes: 'Avatar generation - may require reference image',
  },

  // ==================== IMAGE-TO-VIDEO (I2V) ====================
  {
    id: 'i2v-kling-2.6',
    name: 'Kling 2.6 I2V',
    category: 'i2v',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'The logo gently rotates with soft lighting, cinematic movement',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.6',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
  },
  {
    id: 'i2v-kling-2.5',
    name: 'Kling 2.5 I2V',
    category: 'i2v',
    model: 'kling',
    taskType: 'video_generation',
    input: {
      prompt: 'Smooth zoom out revealing the full image with ambient particles',
      mode: 'std',
      duration: 5,
      aspect_ratio: '16:9',
      version: '2.5',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.14',
    estimatedTime: '~60s',
  },
  {
    id: 'i2v-hailuo',
    name: 'Hailuo I2V',
    category: 'i2v',
    model: 'hailuo',
    taskType: 'video_generation',
    input: {
      prompt: 'The image comes to life with gentle motion and natural movement',
      model: 'i2v-01',
      duration: 6,
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.20',
    estimatedTime: '~120s',
  },
  {
    id: 'i2v-hailuo-director',
    name: 'Hailuo Director I2V',
    category: 'i2v',
    model: 'hailuo',
    taskType: 'video_generation',
    input: {
      prompt: '[Push in,Pan left]smooth cinematic reveal',
      model: 'i2v-01-director',
      duration: 6,
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.20',
    estimatedTime: '~120s',
    notes: 'Camera control mode with directorial movements',
  },
  {
    id: 'i2v-wan-2.6',
    name: 'Wan 2.6 I2V',
    category: 'i2v',
    model: 'Wan',
    taskType: 'wan26-img2video',
    input: {
      prompt: 'The image animates with gentle movement and flowing energy',
      resolution: '720P',
      duration: 5,
      watermark: false,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.40',
    estimatedTime: '~90s',
  },
  {
    id: 'i2v-luma',
    name: 'Luma I2V',
    category: 'i2v',
    model: 'luma',
    taskType: 'video_generation',
    input: {
      prompt: 'Cinematic slow push in with subtle parallax depth effect',
      aspect_ratio: '16:9',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.30',
    estimatedTime: '~90s',
  },
  {
    id: 'i2v-veo-3',
    name: 'Veo 3 I2V',
    category: 'i2v',
    model: 'veo3',
    taskType: 'veo3-video-fast',
    input: {
      prompt: 'The image transforms into a cinematic scene with natural motion',
      aspect_ratio: '16:9',
      duration: '4s',
      resolution: '720p',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~120s',
  },
  {
    id: 'i2v-veo-3.1',
    name: 'Veo 3.1 I2V',
    category: 'i2v',
    model: 'veo3.1',
    taskType: 'veo3.1-video-fast',
    input: {
      prompt: 'Smooth animation of the image with professional camera movement',
      aspect_ratio: '16:9',
      duration: '4s',
      resolution: '720p',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.50',
    estimatedTime: '~120s',
  },
  {
    id: 'i2v-seedance-pro',
    name: 'Seedance Pro I2V',
    category: 'i2v',
    model: 'seedance',
    taskType: 'video_generation',
    input: {
      prompt: 'The image gently moves with organic flowing motion',
      version: '1.0-pro',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.25',
    estimatedTime: '~120s',
  },
  {
    id: 'i2v-seedance-lite',
    name: 'Seedance Lite I2V',
    category: 'i2v',
    model: 'seedance',
    taskType: 'video_generation',
    input: {
      prompt: 'Subtle zoom and motion bringing the still image to life',
      version: '1.0-lite',
    },
    requiresImage: true,
    imageInputField: 'image_url',
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~60s',
  },

  // ==================== IMAGE-TO-IMAGE (I2I) ====================
  {
    id: 'i2i-flux-kontext-dev',
    name: 'Flux Kontext Dev I2I',
    category: 'i2i',
    model: 'Qubico/flux1-kontext-dev',
    taskType: 'img2img',
    input: {
      prompt: 'Transform into a vibrant watercolor painting style, keep the composition',
      guidance_scale: 2.5,
      strength: 0.85,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~10s',
  },
  {
    id: 'i2i-flux-kontext-pro',
    name: 'Flux Kontext Pro I2I',
    category: 'i2i',
    model: 'Qubico/flux-kontext-pro',
    taskType: 'img2img',
    input: {
      prompt: 'Enhance and add dramatic cinematic lighting, professional photography style',
      guidance_scale: 3.0,
      strength: 0.75,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.05',
    estimatedTime: '~15s',
  },
  {
    id: 'i2i-flux-kontext-max',
    name: 'Flux Kontext Max I2I',
    category: 'i2i',
    model: 'Qubico/flux-kontext-max',
    taskType: 'img2img',
    input: {
      prompt: 'Convert to elegant minimalist vector art with clean lines and flat colors',
      guidance_scale: 3.5,
      strength: 0.9,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.08',
    estimatedTime: '~15s',
  },
  {
    id: 'i2i-flux-dev',
    name: 'Flux Dev I2I',
    category: 'i2i',
    model: 'Qubico/flux1-dev',
    taskType: 'img2img',
    input: {
      prompt: 'Reimagine as a 3D rendered scene with soft studio lighting',
      width: 1024,
      height: 1024,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.015',
    estimatedTime: '~10s',
  },
  {
    id: 'i2i-seedream',
    name: 'Seedream 4.0 I2I',
    category: 'i2i',
    model: 'bytedance/seedream-v4.0',
    taskType: 'img2img',
    input: {
      prompt: 'Transform into a luxury brand advertisement style with golden accents',
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~8s',
  },
  {
    id: 'i2i-qwen',
    name: 'Qwen Image I2I',
    category: 'i2i',
    model: 'Qubico/qwen-image',
    taskType: 'img2img',
    input: {
      prompt: 'Redraw in traditional Japanese ink wash painting style',
      width: 1024,
      height: 1024,
    },
    requiresImage: true,
    imageInputField: 'image',
    pollForResult: true,
    estimatedCost: '$0.075',
    estimatedTime: '~10s',
  },

  // ==================== IMAGE GENERATION (T2I) ====================
  {
    id: 'flux-schnell',
    name: 'Flux Schnell',
    category: 'image',
    model: 'Qubico/flux1-schnell',
    taskType: 'txt2img',
    input: {
      prompt: 'A serene Japanese garden with cherry blossoms, koi pond, stone lantern, watercolor style',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.003',
    estimatedTime: '~5s',
  },
  {
    id: 'flux-dev',
    name: 'Flux Dev',
    category: 'image',
    model: 'Qubico/flux1-dev',
    taskType: 'txt2img',
    input: {
      prompt: 'A cozy cabin in the woods with warm light glowing from windows at twilight',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.015',
    estimatedTime: '~10s',
  },
  {
    id: 'flux-kontext',
    name: 'Flux Kontext',
    category: 'image',
    model: 'Qubico/flux-kontext',
    taskType: 'txt2img',
    input: {
      prompt: 'Professional product photography of a ceramic coffee mug on a marble countertop, soft natural light',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~10s',
  },
  {
    id: 'gpt-image-1',
    name: 'GPT-Image-1',
    category: 'image',
    model: 'gpt-4o-image',
    taskType: 'txt2img',
    input: {
      prompt: 'A whimsical illustration of a fox reading a book under a tree',
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.04',
    estimatedTime: '~15s',
    notes: 'Uses chat completions endpoint',
  },
  {
    id: 'gpt-image-1.5',
    name: 'GPT Image 1.5',
    category: 'image',
    model: 'gpt-image-1.5',
    taskType: 'txt2img',
    input: {
      prompt: 'A minimalist logo design of a mountain with sunrise, clean vector style',
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.05',
    estimatedTime: '~15s',
    notes: 'Uses chat completions endpoint',
  },
  {
    id: 'qwen-image',
    name: 'Qwen Image',
    category: 'image',
    model: 'Qubico/qwen-image',
    taskType: 'txt2img',
    input: {
      prompt: 'An elegant calligraphy brush painting of bamboo with a red seal stamp',
      width: 1024,
      height: 1024,
    },
    pollForResult: true,
    estimatedCost: '$0.075',
    estimatedTime: '~10s',
  },
  {
    id: 'nano-banana',
    name: 'Nano Banana',
    category: 'image',
    model: 'nano-banana',
    taskType: 'txt2img',
    input: {
      prompt: 'A photorealistic still life of fresh fruits in a wooden bowl, natural window light',
    },
    pollForResult: true,
    estimatedCost: '$0.03',
    estimatedTime: '~5s',
  },
  {
    id: 'nano-banana-pro',
    name: 'Nano Banana Pro',
    category: 'image',
    model: 'nano-banana-pro',
    taskType: 'txt2img',
    input: {
      prompt: 'Luxury perfume bottle on black marble surface, dramatic studio lighting, product photography',
    },
    pollForResult: true,
    estimatedCost: '$0.105',
    estimatedTime: '~8s',
  },
  {
    id: 'seedream-4.0',
    name: 'Seedream 4.0',
    category: 'image',
    model: 'bytedance/seedream-v4.0',
    taskType: 'txt2img',
    input: {
      prompt: 'A majestic eagle soaring above snow-capped mountains at golden hour, cinematic',
    },
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~8s',
  },
  {
    id: 'z-image-turbo',
    name: 'Z Image Turbo',
    category: 'image',
    model: 'z-image-turbo',
    taskType: 'txt2img',
    input: {
      prompt: 'Modern minimalist interior design living room with large windows and natural light',
    },
    pollForResult: true,
    estimatedCost: '$0.01',
    estimatedTime: '~3s',
  },

  // ==================== AUDIO GENERATION ====================
  {
    id: 'diffrhythm',
    name: 'DiffRhythm',
    category: 'audio',
    model: 'Qubico/diffrhythm',
    taskType: 'txt2audio-base',
    input: {
      lyrics: '[verse]\nGentle morning light\nSoft breeze through the trees\n[chorus]\nNature sings along\nPeaceful melody',
      style_prompt: 'ambient calm instrumental',
    },
    pollForResult: true,
    estimatedCost: '$0.05',
    estimatedTime: '~30s',
  },
  {
    id: 'udio',
    name: 'Udio',
    category: 'audio',
    model: 'music-u',
    taskType: 'generate_music',
    input: {
      gpt_description_prompt: 'calm ambient piano music, gentle and relaxing, nature sounds',
      negative_tags: 'aggressive loud distorted',
      lyrics_type: 'instrumental',
      seed: -1,
    },
    pollForResult: true,
    estimatedCost: '$0.10',
    estimatedTime: '~60s',
  },
  {
    id: 'f5-tts',
    name: 'F5 TTS',
    category: 'audio',
    model: 'Qubico/tts',
    taskType: 'zero-shot',
    input: {
      gen_text: 'Welcome to the AI Video Production Studio. This is a test of the text to speech system.',
      ref_audio: '',
      ref_text: '',
    },
    pollForResult: true,
    estimatedCost: '$0.025',
    estimatedTime: '~10s',
    notes: 'Requires ref_audio for voice cloning, or uses default voice',
  },
  {
    id: 'mmaudio',
    name: 'MMAudio',
    category: 'audio',
    model: 'Qubico/mmaudio',
    taskType: 'video2audio',
    input: {
      prompt: 'gentle nature sounds, birds chirping, wind rustling leaves',
      negative_prompt: 'loud noise music speech',
      steps: 20,
    },
    pollForResult: true,
    estimatedCost: '$0.03',
    estimatedTime: '~15s',
    notes: 'Video-to-audio - may require video input for full test',
  },
  {
    id: 'ace-step',
    name: 'ACE Step AI',
    category: 'audio',
    model: 'Qubico/ace-step',
    taskType: 'text2audio',
    input: {
      lyrics: '[inst]',
      style_prompt: 'soft ambient electronic chill',
      negative_prompt: 'noise distortion',
    },
    pollForResult: true,
    estimatedCost: '$0.05',
    estimatedTime: '~30s',
  },
  {
    id: 'moshi',
    name: 'Moshi',
    category: 'audio',
    model: 'moshi',
    taskType: 'conversation',
    input: {
      prompt: 'Hello, can you hear me?',
    },
    pollForResult: true,
    estimatedCost: '$0.02',
    estimatedTime: '~10s',
    notes: 'Conversational AI - may be on waitlist',
  },

  // ==================== LLM ====================
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'llm',
    model: 'deepseek-chat',
    taskType: 'chat-completion',
    input: {
      messages: [
        { role: 'user', content: 'Respond with exactly: "PiAPI DeepSeek test successful"' },
      ],
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.001',
    estimatedTime: '~3s',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    category: 'llm',
    model: 'gpt-4o',
    taskType: 'chat-completion',
    input: {
      messages: [
        { role: 'user', content: 'Respond with exactly: "PiAPI GPT-4o test successful"' },
      ],
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.005',
    estimatedTime: '~3s',
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'llm',
    model: 'claude-sonnet-4-20250514',
    taskType: 'chat-completion',
    input: {
      messages: [
        { role: 'user', content: 'Respond with exactly: "PiAPI Claude test successful"' },
      ],
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.003',
    estimatedTime: '~3s',
  },
  {
    id: 'deep-research',
    name: 'Deep Research',
    category: 'llm',
    model: 'deep-research',
    taskType: 'chat-completion',
    input: {
      messages: [
        { role: 'user', content: 'What is 2+2? Answer briefly.' },
      ],
    },
    endpoint: 'chat-completions',
    pollForResult: false,
    estimatedCost: '$0.01',
    estimatedTime: '~10s',
    notes: 'Deep research model - may take longer',
  },
];

export function getTestsByCategory(category: string): PiAPITestDefinition[] {
  return PIAPI_TEST_DEFINITIONS.filter(t => t.category === category);
}

export function getTestById(id: string): PiAPITestDefinition | undefined {
  return PIAPI_TEST_DEFINITIONS.find(t => t.id === id);
}
